### ISSUE TITLE
程序跑不起来，请作者指教

### ISSUE THREAD

**Issue by arghcz** [WangRv/uiKline#1]
我是个新手，正在写类似的东西  看了您的代码 很有启发，就是运行的时候 有上面的错误 ，跑不起来。
具体错误提示：
Traceback (most recent call last):
  File "d:/python/gitHub code/stock_examples/uiKline-master/vnpy2_chart_Demo.py", line 76, in <module>
    widget.add_plot("volume", maximum_height=200)
  File "d:\python\gitHub code\stock_examples\uiKline-master\chart\everDataAxisWidget.py", line 202, in add_plot
    hide_x_axis)
  File "d:\python\gitHub code\stock_examples\uiKline-master\chart\everDataAxisWidget.py", line 226, in _made_plot
    plot = pg.PlotItem(axisItems={"bottom": self._common_x_axis})
  File "D:\anaconda3\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 158, in __init__
    self.setAxisItems(axisItems)
  File "D:\anaconda3\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 325, in setAxisItems
    if axis != self.axes[k]["item"]:
KeyError: 'bottom'

万分感谢

**Comment by WangRv** [comment]
报错没贴完整，提示是字典少了关键字参数buttom 应该是button

**Comment by arghcz** [comment]
万分感谢您的回复，我的感觉应该是 bottom 不是button 
是在 pg.PlotItem(axisItems={"bottom": self._common_x_axis}) 里面的，不知道对不对
具体错误信息见附件
麻烦了 谢谢
另外 有 好的pyqt 特别是 pyqtgraph 方面的书 或者学习网站推荐吗   谢谢


发送自 Windows 10 版邮件应用

发件人: WangRv
发送时间: 2020年12月7日 17:26
收件人: WangRv/uiKline
抄送: arghcz; Author
主题: Re: [WangRv/uiKline] 程序跑不起来，请作者指教 (#1)

报错没贴完整，提示是字典少了关键字参数buttom 应该是button
